### ISSUE TITLE
请求报错Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag

### ISSUE THREAD

**Issue by guoliping717** [Duanzihuang/alipay_for_node#1]
crypto.js:286
  var ret = this._handle.sign(toBuf(key), null, passphrase);
                         ^

Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
    at Error (native)
    at Sign.sign (crypto.js:286:26)
    at Object.exports.getParamsQueryAndSign (E:\node\alipay_for_node\src\alipay_for_node\lib\sign.js:48:24)
    at Alipay.getLastRequestStr (E:\node\alipay_for_node\src\alipay_for_node\index.js:86:30)
    at IncomingMessage.req.on (E:\node\alipay_for_node\src\app.js:70:45)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Alipay_For_Node@1.0.0 start: `node src/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Alipay_For_Node@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-04-16T09_36_51_404Z-debug.log

**Comment by guoliping717** [comment]
可以请教下你的支付宝开发者中心是如何设置的呢

**Comment by Duanzihuang** [comment]
你要配置啥?



深圳中心前端与移动开发教研部  讲师  黄伟
 
专注于JavaEE、Android、PHP、UI设计、iOS、前端与移动开发、C/C++、网络营销、云计算、Python工程师的培养
地址：深圳市宝安区留仙二路中粮商务公园3栋17层
邮编：518000
电话：400-618-9090
网址：http://www.itheima.com
邮件：huangwei@itcast.cn
 
发件人： guoliping717
发送时间： 2019-04-16 17:54
收件人： Duanzihuang/alipay_for_node
抄送： Subscribed
主题： Re: [Duanzihuang/alipay_for_node] 请求报错Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag (#1)
可以请教下你的支付宝开发者中心是如何设置的呢
―

**Comment by guoliping717** [comment]
你好请教下  我就是想要使用node.js配置支付宝的请求接口 拼接url返回跳转支付宝支付链接 我看到你那个文章并且按照你那个进行配置后一直报错 Re: [Duanzihuang/alipay_for_node] 请求报错Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag (#1)  还望指教一二







------------------ 原始邮件 ------------------
发件人: "段子黄"<notifications@github.com>;
发送时间: 2019年4月16日(星期二) 晚上8:28
收件人: "Duanzihuang/alipay_for_node"<alipay_for_node@noreply.github.com>;
抄送: "Gordon"<1553420481@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Duanzihuang/alipay_for_node] 请求报错Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag (#1)



你要配置啥? 
 
 
 
 深圳中心前端与移动开发教研部  讲师  黄伟 
   
 专注于JavaEE、Android、PHP、UI设计、iOS、前端与移动开发、C/C++、网络营销、云计算、Python工程师的培养 
 地址：深圳市宝安区留仙二路中粮商务公园3栋17层 
 邮编：518000 
 电话：400-618-9090 
 网址：http://www.itheima.com 
 邮件：huangwei@itcast.cn 
   
 发件人： guoliping717 
 发送时间： 2019-04-16 17:54 
 收件人： Duanzihuang/alipay_for_node 
 抄送： Subscribed 
 主题： Re: [Duanzihuang/alipay_for_node] 请求报错Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag (#1) 
 可以请教下你的支付宝开发者中心是如何设置的呢 
 ―

**Comment by guoliping717** [comment]
我是把您这边的代码clone下来后修改后运行就报这个错误，这个不知道啥原因

**Comment by guoliping717** [comment]
是不是我的支付宝开发者中心密钥啥设置错误了

**Comment by Duanzihuang** [comment]
感觉是你生成的私钥不对，加密出了问题，我提供了两种加密方式，RSA和RSA2，请注意区分哦，还有私钥要加上固定的头，参考我提供的私钥文件



    
    
        
            
                
                    
                        
                    
                    
                        
                            huangwei
                            
                            
                                
                                    邮箱：huangwei@itcast.cn
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2019年04月16日 20:44，guoliping717 写道： 是不是我的支付宝开发者中心密钥啥设置错误了



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Duanzihuang/alipay_for_node","title":"Duanzihuang/alipay_for_node","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Duanzihuang/alipay_for_node"}},"updates":{"snippets":[{"icon":"PERSON","message":"@guoliping717 in #1: 是不是我的支付宝开发者中心密钥啥设置错误了 "}],"action":{"name":"View Issue","url":"https://github.com/Duanzihuang/alipay_for_node/issues/1#issuecomment-483643445"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Duanzihuang/alipay_for_node/issues/1#issuecomment-483643445",

"url": "https://github.com/Duanzihuang/alipay_for_node/issues/1#issuecomment-483643445",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by guoliping717** [comment]
你这边的生成密钥的工具是使用的那个官方的那个工具？  还是OpenSSL? 我现在的操作是使用的那个工具PKCS1(非JAVA适用) 2048 长度的这个  然后我把公钥放到支付宝的开发者RSA2(SHA256)密钥的位置 私钥我放到你这个项目rsa2_private_key.pem文件中，这样的操作是否正确 跟您这边是否一样？

**Comment by guoliping717** [comment]
![image](https://user-images.githubusercontent.com/32388964/56256896-224d6280-60fd-11e9-9418-ddd092522b22.png)
![image](https://user-images.githubusercontent.com/32388964/56256930-3d1fd700-60fd-11e9-840e-24311a5c0fe2.png)
这是我的开发者中心沙箱中心  你这边是新建的项目  还是直接使用的沙箱？

**Comment by guoliping717** [comment]
感谢楼主的耐心解答和支持，这个报错问题已经解决，在这里总结下 这个问题出现原因是签名不正确，并且使用的是官方的工具这个
![image](https://user-images.githubusercontent.com/32388964/56259217-d999a780-6104-11e9-83ea-52fe6c8f0cde.png)
这个工具生成的密钥老是无法匹配成功。最后解决方法这个参考这个链接
https://openclub.alipay.com/read.php?tid=1486&fid=46 
根据这个链接所生成的就不会有问题，再次感谢楼主的解答和代码，给个star支持下，同时也给后边遇到这种问题的朋友一个参考。再次感谢

**Comment by 1032740078** [comment]
我也出现这个报错，经过调试，把应用私钥通过“支付宝开放平台秘钥工具”->"格式转换"，转成pkcs1格式后，就可以了
